# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
  
pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.4'
  displayName: 'Use Python 3.10.4'

- script: |
    sudo apt update
    sudo apt install ffmpeg

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install requirements'    

- script: |
    cp --recursive example-database database
  displayName: 'Configure database'

- script: |
    python downloader.py
  displayName: 'Validate MP3 download function'