# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main
  
pool:
  vmImage: windows-2022

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.12'
  displayName: 'Use Python 3.9.12'

- script: |
    Xcopy /E /I example-database database
  displayName: 'Configure database'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install & verify requirements'

# Temporarly turned of to safe time and test other things
#- script: |
#    python downloader.py
#  displayName: 'Validate MP3 download function'